name: afristory
version: 1.0.0
title: AfriStory
description: Plateforme panafricaine de Webtoons, BDs et Romans Illustrés
homepage: https://afristory.com
language: TypeScript
topics:
  - react
  - typescript
  - webtoon
  - manga
  - bd
  - comic
  - firebase
  - framer-motion
  - tailwind-css
  - tailwind
  - african
  - creative-platform
  - digital-platform
  - publishing
  - comics-reader
license: Proprietary
author: AfriStory Team <contact@afristory.com>
funding:
  url: https://afristory.com/subscription